export enum SortBy {
    NAME_ASC = 'NAME_ASC',
    NAME_DESC = 'NAME_DESC',
    CREATED_AT_ASC = 'CREATED_AT_ASC', 
    CREATED_AT_DESC = 'CREATED_AT_DESC',
    LAST_PURCHASE_ASC = 'LAST_PURCHASE_ASC',
    LAST_PURCHASE_DESC = 'LAST_PURCHASE_DESC'
}